### ISSUE TITLE
Πόσες εκδόσεις πρέπει να παραδώσουμε;

### ISSUE THREAD

**Issue by anagno** [anagno/BookShop#1]
@GiannisVid  @liolisgeo  Ξέρει κανείς πόσες εκδόσεις του προγράμματος πρέπει να παραδώσουμε ;;; Μία τελική ή πρέπει να κάνουμε και ενδιάμεσα στάδια ;;;

**Comment by GiannisVid** [comment]
Νομίζω μόνο τελικό δίνουμε.

**Comment by anagno** [comment]
Μακάρι διότι τα περιεχόμενα αναφέρουν δυο υλοποιήσεις ...

**Comment by liolisgeo** [comment]
Νομίζω είχε πει ότι θέλει και 2-3 εκδόσεις , αλλά δεν ξέρω αν είναι υποχρεωτικό. 

Να κάνω μια ερώτηση για την 1η εργασία του εργαστηρίου δίκτυα. Πώς βάζουμε τη subnet mask στα τερματικά? Βάζω την ip 10.1.1.32 και μετά 255.255.255.248 , αλλά δεν τη δέχεται… με 255.255.255.192 την παίρνει , αλλά μας δίνει στη εικόνα ip 10.1.1.32/29…






Sent from Windows Mail





From: Vasilis-Thanos Anagnostopoulos
Sent: ‎Tuesday‎, ‎February‎ ‎17‎, ‎2015 ‎7‎:‎40‎ ‎PM
To: anagno/BookShop
Cc: liolisgeo





Μακάρι διότι τα περιεχόμενα αναφέρουν δυο υλοποιήσεις ...

**Comment by anagno** [comment]
Τί γράφει όταν δεν την δέχεται ;;;

**Comment by liolisgeo** [comment]
invalid ip for this subnet mask entered!






Sent from Windows Mail





From: Vasilis-Thanos Anagnostopoulos
Sent: ‎Tuesday‎, ‎February‎ ‎17‎, ‎2015 ‎8‎:‎53‎ ‎PM
To: anagno/BookShop
Cc: liolisgeo




Τί γράφει όταν δεν την δέχεται ;;;
