### ISSUE TITLE
Διαγράμματα

### ISSUE THREAD

**Issue by GiannisVid** [anagno/BookShop#10]
Στο http://www.dmst.aueb.gr/dds/ism/oo/indexw.htm παρουσιάζονται τα διαγράμματα uml σε κατηγορίες.
Το διάγραμμα εξαρτημάτων (component diagram) και το διάγραμμα ανάπτυξης (deployment diagram) είναι καλύτερο να γίνουν από 'σένα Βασίλη γιατί αναφέρονται στον πηγαίο κώδικα.

**Comment by anagno** [comment]
Τα ανέβασα. Για κοίτα άμα έχουν καμιά χοντράδα που δεν πήρα είδηση. Και ξέρεις άμα έχει και κανένα παράδειγμα το βιβλίο της Βίρβου και αν ναι τί σελίδα ;;;

**Comment by anagno** [comment]
@GiannisVid Να σε πω ... Μετακίνησε τα διαγράμματα στο doc/images και μετανόμασε τα σε CamelCase ... (Δεν το κάνω εγώ για να μην σου δημιουργήσω τυχόν conflict ... Όταν θα θες να μάθεις git θα στο δείξω και αυτό ...)
Και αφού το κάνεις αυτό κοίταξε και τα δικά μου διότι νομίζω υπάρχουν κάποια κοινά ...
