### ISSUE TITLE
Τεχνική Έκθεση

### ISSUE THREAD

**Issue by anagno** [anagno/BookShop#12]
@GiannisVid  @liolisgeo  @eirinichr Όποιος έχει γράψει τπτ στην τεχνική έκθεση ας το ανεβάσει για να αρχίσει η σύνθεση και να διαπιστώσουμε τί λείπει ...

**Comment by anagno** [comment]
Να ρωτήσω ... Τί λειπει από την τεχνική έκθεση (εκτός από συνοχή, και την περιγραφή των επιπρόσθετων διαγραμμάτων) ;;;

**Comment by liolisgeo** [comment]
Τα διαγράμματα που έκανε ο Γιάννης τα έχεις δει? Γιατί δεν τα βλέπω στο pdf






Sent from Windows Mail





From: Vasilis-Thanos Anagnostopoulos
Sent: ‎Thursday‎, ‎April‎ ‎30‎, ‎2015 ‎12‎:‎59‎ ‎AM
To: anagno/BookShop
Cc: liolisgeo





Να ρωτήσω ... Τί λειπει από την τεχνική έκθεση (εκτός από συνοχή, και την περιγραφή των επιπρόσθετων διαγραμμάτων) ;;;

**Comment by liolisgeo** [comment]
Στο git τα έχεις διαγράψει σαν duplicate , αλλά δεν είναι περασμένα στην τεχνική έκθεση.






Sent from Windows Mail





From: Vasilis-Thanos Anagnostopoulos
Sent: ‎Thursday‎, ‎April‎ ‎30‎, ‎2015 ‎12‎:‎59‎ ‎AM
To: anagno/BookShop
Cc: liolisgeo





Να ρωτήσω ... Τί λειπει από την τεχνική έκθεση (εκτός από συνοχή, και την περιγραφή των επιπρόσθετων διαγραμμάτων) ;;;

**Comment by anagno** [comment]
Ειναι στα images  μεσα... Γραψε που να τα βαλω και θα τα ενσωματωσω ...

Ο χρήστης liolisgeo <notifications@github.com> έγραψε:

Στο git τα έχεις διαγράψει σαν duplicate , αλλά δεν είναι περασμένα στην τεχνική έκθεση.






Sent from Windows Mail





From: Vasilis-Thanos Anagnostopoulos
Sent: ‎Thursday‎, ‎April‎ ‎30‎, ‎2015 ‎12‎:‎59‎ ‎AM
To: anagno/BookShop
Cc: liolisgeo





Να ρωτήσω ... Τί λειπει από την τεχνική έκθεση (εκτός από συνοχή, και την περιγραφή των επιπρόσθετων διαγραμμάτων) ;;;

—
Reply to this email directly or view it on GitHub.

---

**Comment by anagno** [comment]
Μεσα στο τεχ σημειωσε που θες να μπουν ...

Ο χρήστης liolisgeo <notifications@github.com> έγραψε:

Στο git τα έχεις διαγράψει σαν duplicate , αλλά δεν είναι περασμένα στην τεχνική έκθεση.






Sent from Windows Mail





From: Vasilis-Thanos Anagnostopoulos
Sent: ‎Thursday‎, ‎April‎ ‎30‎, ‎2015 ‎12‎:‎59‎ ‎AM
To: anagno/BookShop
Cc: liolisgeo





Να ρωτήσω ... Τί λειπει από την τεχνική έκθεση (εκτός από συνοχή, και την περιγραφή των επιπρόσθετων διαγραμμάτων) ;;;

—
Reply to this email directly or view it on GitHub.

---

**Comment by liolisgeo** [comment]
ok θα το δω ολοκληρωμένο αύριο και θα σου πω τι χρειάζεται 






Sent from Windows Mail





From: Vasilis-Thanos Anagnostopoulos
Sent: ‎Friday‎, ‎May‎ ‎8‎, ‎2015 ‎9‎:‎59‎ ‎PM
To: anagno/BookShop
Cc: liolisgeo




Μεσα στο τεχ σημειωσε που θες να μπουν ...

Ο χρήστης liolisgeo <notifications@github.com> έγραψε:

Στο git τα έχεις διαγράψει σαν duplicate , αλλά δεν είναι περασμένα στην τεχνική έκθεση.






Sent from Windows Mail





From: Vasilis-Thanos Anagnostopoulos
Sent: ‎Thursday‎, ‎April‎ ‎30‎, ‎2015 ‎12‎:‎59‎ ‎AM
To: anagno/BookShop
Cc: liolisgeo





Να ρωτήσω ... Τί λειπει από την τεχνική έκθεση (εκτός από συνοχή, και την περιγραφή των επιπρόσθετων διαγραμμάτων) ;;;

—
Reply to this email directly or view it on GitHub.

---

**Comment by liolisgeo** [comment]
Basili gia des tis allages na doume to apotelesma kai an xreiazetai kai kati allo
