### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by GiannisVid** [anagno/BookShop#14]
@anagno Βασίλη, όταν πατάς search χωρίς να δώσεις στοιχεία, επιστρέφει όλα τα βιβλία. Επίσης καλό θα ήταν να υπάρχει επιλογή "Δες όλα τα βιβλία" που να κάνει ότι και αυτό που λέει!

**Comment by eirinichr** [comment]
Από τη στιγμή που δεν βάζει κάτι στο search, ας δείχνει όλα τα βιβλία... Αν όντως έχουμε όρεξη να το κάνουμε θα ήταν όντως καλύτερο (να πετάει και μήνυμα ότι "δεν βάλατε κάτι στο search, δοκιμάστε ξανά" κτλ) αλλά δε νομίζω ότι είναι απαραίτητο... Περί ορέξεως...;-)

**Comment by anagno** [comment]
https://github.com/anagno/BookShop/commit/18436e927b670dfca03e3e0058f7b0adc194080f
https://github.com/anagno/BookShop/commit/121d554913f5398a277f243aae69bca15a5c110a
