### ISSUE TITLE
Στοιχήματα

### ISSUE THREAD

**Issue by anagno** [anagno/BookShop#15]
@GiannisVid  @liolisgeo @eirinichr Ακούω μέχρι πότε θα έχουν βγει η βαθμολογίες !
Εγώ λέω μέχρι την Τετάρτη ...

**Comment by GiannisVid** [comment]
Εγώ λέω μια βδομάδα.
Στοίχημα 2GB.

Στις 11 Μαΐου 2015 - 9:35 μ.μ., ο χρήστης Vasilis-Thanos Anagnostopoulos <
notifications@github.com> έγραψε:

**Comment by liolisgeo** [comment]
Εγώ λέω Παρασκευή με 5:1 αρχικό...
Στις 12 Μαϊ 2015 12:29 ΜΜ, ο χρήστης "Giannis" <notifications@github.com>
έγραψε:
