### ISSUE TITLE
Οργάνωση βάσης

### ISSUE THREAD

**Issue by anagno** [anagno/BookShop#2]
@GiannisVid  Κοίτα λίγο την προηγούμενη υλοποίηση για την βάση ... Πως σου φαίνετε και τι πρέπει να αλλάξει;;; Η λόγικη με την οποία την έφτιαξα είναι εδώ : https://github.com/anagno/book_management/blob/master/doc/bin/books_databases.pdf

![erdiagram](https://cloud.githubusercontent.com/assets/5438380/6284206/6d97ccb6-b8f6-11e4-9dc4-9fa6b9337711.jpeg)
![relationalmodel](https://cloud.githubusercontent.com/assets/5438380/6284208/74ed27b8-b8f6-11e4-9e16-915339badb60.jpeg)

**Comment by GiannisVid** [comment]
Ερώτηση!
Τελικά τι της έχουμε πει οτι θα κάνουμε;;; Ρωτάω γιατί εγώ δεν ήμουν εκεί εκείνη τη μέρα. Αν της είπαμε για σύστημα διαχείρισης βιβλιοθήκης, τότε δεν χρειάζεται η εξειδίκευση της έκδοσης μιας και η βιβλιοθήκη δεν μπορεί να δανείσει eBook! 
Αν όμως της είπαμε για ηλεκτρονικό βιβλιοπωλείο είμαστε κομπλέ. Επίσης να τονίσω ότι θεωρητικά κάθε βιβλίο έχει σαν χαρακτηριστικό ένα isbn (και barcode) το οποίο είναι μοναδικό για κάθε έκδοση (άλλο isbn ένα έντυπο και άλλο ένα eBook) και άρα μπορεί να χρησιμοποιηθεί σαν id!

**Comment by GiannisVid** [comment]
ΥΓ: Sorry που άργησα να απαντήσω

**Comment by anagno** [comment]
Σύστημα διαχείριση βιβλιοθήκης καταλήξαμε.
Οκ δεν θα γίνει εξειδίκευση (αυτό είχε ξεμείνει από την παλιά εργασία). 
Άρα απλώς να βάλω σαν πρωτεύον κλειδί το isbn και να βγάλω τα πολλά indtifiers ???

**Comment by anagno** [comment]
Ακόμα κάθε έκδοση βιβλίου (π.χ. 1η έκδοση του μαθαίνω C++, 2η έκδοση κ.λ.π.) θα έπρεπε να έχουν διαφορετικό isbn???

**Comment by GiannisVid** [comment]
Ναι εννοείται!!! 
πχ.
http://www.mgiurdas.gr/biblia/c-programmatismos-3i-ekdosi 
http://www.mgiurdas.gr/biblia/c-programmatismos-5i-ekdosi
Επίσης υποτίθεται ότι το isbn είναι 13-ψήφιο αλλά πολύ χρησιμοποιούν 10ψήφιο ή 11ψήφιο (παλιό σύστημα) οπότε καλύτερα να μην το πολύ μπλέξουμε...

**Comment by anagno** [comment]
1)Κρατάμε τα 13 ψηφία να τελειώνει ... Νομίζω μπορείς να μετατρέψεις και τα άλλα έτσι και αλλιώς ...

2)Από την στιγμή που έχει κάθε έκδοση διαφορετικό isbn το χρησιμοποιούμε για να ταυτοτποιούμε την έκδοση και έχουμε διαφορετικό εσωτερικό id για τα βιβλία (που έχουν πολλές εκδόσεις )

**Comment by anagno** [comment]
Ξέφυγε τπτ;;;

![erdiagram](https://cloud.githubusercontent.com/assets/5438380/6313638/cbc9f524-b9bf-11e4-8e6a-a7cd12f5803f.png)

Τους χρήστες θα τους συνδέσω μετά...

**Comment by GiannisVid** [comment]
User και book συνδέονται για να φαίνεται ποιος έχει (δανειστεί) ποιο βιβλίο.
Το απόθεμα θα το βάλουμε σαν χαρακτηριστικό;

**Comment by anagno** [comment]
αυτό είναι προκύπτον χαρακτηριστικό ... Θα το ενσωματόσουμε στην κλάση αν χρείαζετε να φαίνετε ...

**Comment by anagno** [comment]
έτοιμο. και με το προκύπτον χαρακτηριστικό ...
![erdiagram](https://cloud.githubusercontent.com/assets/5438380/6313696/de5c211e-b9c2-11e4-8d1b-dc82f6b9c69d.png)

**Comment by anagno** [comment]
παρα είμαι καλός ... σκέτο κουκλί εινια ... :-P

**Comment by anagno** [comment]
και μάλλον ως υλοποίηση κάτι τέτοιο ... http://www.java2s.com/Code/SQL/Select-Clause/SubqueriesAsCalculatedColumnsSimpleSubqueries.htm

**Comment by GiannisVid** [comment]
Παιχτούρα είσαι, παιχτούρα!

**Comment by liolisgeo** [comment]
Εγω θυμαμαι για συστημα βιβλιοθηκης ειπαμε οχι βιβλιοπωλειο !!Νομιζω ειναι
και πιο απλο να γινει ε?
Στις 21 Φεβ 2015 11:11 ΠΜ, ο χρήστης "Giannis" <notifications@github.com>
έγραψε:

**Comment by liolisgeo** [comment]
Ε!τωρα ειδα ολο το διαλογο!το εχετε λυσει!!!ωραια νομιζω η παρεμβαση μου
ηταν καθοριστικη...
Στις 21 Φεβ 2015 1:07 ΜΜ, ο χρήστης "giorgos liolis" <gpith00@gmail.com>
έγραψε:

**Comment by anagno** [comment]
Παιδιά όσα έχω κάνει είναι για σύστημα διαχείρισης βιβλιοθήκης... Όποιος διαφωνεί να το πει τώρα διότι όσο πιο αργά τόσο πιο αγγούρι ... Και εγώ τα αγγούρια τα θέλω μόνο στις σαλάτες ..

**Comment by GiannisVid** [comment]
χαχαχα

**Comment by GiannisVid** [comment]
![default](https://cloud.githubusercontent.com/assets/7192550/6313897/332c9234-b9cb-11e4-8b2d-4a07e3f668f7.jpg)

**Comment by anagno** [comment]
χαχαχα

**Comment by anagno** [comment]
(Να σας θυμήσω πως όλα αυτά είναι προσβάσιμα από όλους ... Άρα παραδίδοντας το repository θα μπορεί να τα δει και αυτά ... Εκτός αν κάποιος κάτσει και τα διαγράψει ένα ένα ...)

**Comment by anagno** [comment]
(και αφού λέμε για σχολιασμούς θα πρέπει μετά κάποιος να λογοκρίνει τα σχόλια του κώδικα μου ... Προειδοποίησα ... Νίπτω τας χείρας μου ...)

**Comment by liolisgeo** [comment]
χμ ενδιαφερον!
Στις 21 Φεβ 2015 1:13 ΜΜ, ο χρήστης "Vasilis-Thanos Anagnostopoulos" <
notifications@github.com> έγραψε:

**Comment by anagno** [comment]
http://stackoverflow.com/questions/184618/what-is-the-best-comment-in-source-code-you-have-ever-encountered
http://thedailywtf.com/

**Comment by anagno** [comment]
Εκλέξτε το !!! Τώρα είναι η ευκαιρία σας να μιλήσετε ... Αλλιώς μετά σιωπή ...
![relationalmodel dia](https://cloud.githubusercontent.com/assets/5438380/6313952/7103f6ee-b9ce-11e4-9468-9a687756eae1.png)

@GiannisVid Πρόσθεσε μου τα πεδία τα οποία θα χρειαστούμε ακόμα ...

**Comment by GiannisVid** [comment]
Authors n n Writes (Σε κάθε βιβλίο μπορεί να είναι 2-3 συγγραφείς - Συλλογικό έργο) - Αυτό όμως ψιλοπροεραιτικά.
Και κάτι μου φαίνεται περίεργο στο books categories. Πολλά n βιβλία σε 1 κατηγορία δεν πρέπει να είναι;;;
κατά τα άλλα super!

**Comment by anagno** [comment]
Όπως είναι δομημένη η βάση υποστηρίζει βιβλίο από πολλούς συγγραφείς ... Κοίτα το καλύτερα ...

Στις κατηγορίες είναι το αντίθετο ... Πολλές κατηγορίες σε ένα βιβλίο ...

Δεν χρειάζετε να αποθηκεύσουμε τπτ άλλο για τους συγγραφείς για τους εκδότες κ.λ.π. ;;;; (πάω να φάω ... έρχομαι σε λίγο ...)

**Comment by GiannisVid** [comment]
1. Σωστός
2. Νομίζω με τις κατηγορίες πρέπει να είναι αντίθετα. Κάθε βιβλίο ανήκει σε μια κατηγορία!
3. Εκδότες νομίζω πρωτεύων κλειδί είναι το όνομα aka η επωνυμία της εταιρείας! πχ Να μην βάζεις εκδότη:  050 - Ψυχογιός και 051 - Ψυχογιός. Αν και για τις ανάγκες του συγκεκριμένου συστήματος, ο εκδότης μπορεί να είναι χαρακτηριστικό της έκδοσης και όχι ξεχωριστή οντότητα!

**Comment by anagno** [comment]
1) Το ξέρω ... :-P
2) Μπα ... Νομίζω ότι πολλά βιβλία ανήκουν πάνω από μία κατηγορία ... (π.χ. χάρρυ πότερ, άρχοντας των δακτυλιδιών κ.λ.π. )
3) Αν είναι να μπει κάτι ως πρωτεύον κλειδί θα έμπαινε το ΑΦΜ. Και επειδή νόμιζα ότι θα αποθηκεύαμε διευθύνσεις τηλέφωνα κ.λ.π. μπήκε ως ξεχωριστή ενότητα ... Θα μπορούσαμε να βάλουμε διάφορα τέτοια ... Εσείς τί αποθηκεύετε στην εταιρεία ;;;

**Comment by GiannisVid** [comment]
Εμείς αποθηκεύουμε τα πάντα (ΑΦΜ και ιστορίες) και πρωτεύον κλειδί έχουμε το id γιατί πολλούς εκδότες τους έχουμε και παρακαταθήκη, οπότε έχει διαφορετική πολιτική από την αγορά! Εμείς όμως έχουμε απ' ευθείας εμπορική συναλλαγή με τους εκδότες! Μια βιβλιοθήκη δεν έχει απαραίτητα απ' ευθείας! πχ. το αμερικάνικο κολέγιο δίνει σε εμάς παραγγελίες με διάφορους εκδότες, ή μπορεί να στηρίζεται σε δωρεές βιβλίων ή οτιδήποτε. Γενικότερα, ένας βιβλιοθηκάριος δεν ενδιαφέρεται για τα στοιχεία ενός εκδότη! Τέλος, όσον αφορά το ΑΦΜ, τι γίνεται με εκδότες που έχουν κλείσει (άρα δεν έχουμε ιδέα ποιο είναι το αφμ τους και δεν μας ενδιαφέρει μιας και έχουν κλείσει!); Anyway...δεν θα σκάσουμε και για τη βάση! Super είναι και έτσι!

**Comment by anagno** [comment]
@liolisgeo, @eirinichr Καλώς τότε ... Το αφήνουμε έτσι και άμα χρειαστεί προσθέτουμε μερικά ακόμα στοιχεία άμα χρειαστεί ... Απλώς όπως είπαμε καλό είναι να συμβεί στο  τώρα και όχι στο απώτερο μέλλον... Άρα όποιος έχει καμιά ιδέα ας την πει τώρα ...

**Comment by GiannisVid** [comment]
Δεν αλλάζουμε τίποτα!
Δεν διαπραγματευόμαστε!
Δεν εκβιαζόμαστε!

**Comment by anagno** [comment]
Το ανεβάζω διότι έκανα μερικές αισθητικές αλλαγές
![relationalmodel](https://cloud.githubusercontent.com/assets/5438380/6314100/94e2e6d4-b9d7-11e4-9aa6-8a422a288985.png)

Θα γράψω στο pdf πως δημιουργούμε την βάση και στην MySql και θα το σπρώξω να το δείτε ...

**Comment by anagno** [comment]
Τα ανέβασα !!! Δημιούργησα και την βάση στον server !!!! Όποιος θέλει αλλαγές άμεσα να το πει αλλιώς να σιωπήσει για πάντα ...
