### ISSUE TITLE
Template εμφάνισης...

### ISSUE THREAD

**Issue by anagno** [anagno/BookShop#3]
@GiannisVid , @liolisgeo , @eirinichr Ετοίμασα και το  domain (tme119.anagno.me). Προς το παρόν έχει μόνο βλακείες ...  Θέλω να μου φτιάξει κάποιος ένα χαζό template στην html για να δω πως θα είναι η εμφάνιση και να αρχίσουμε να το φτιάχνουμε ... Δεν το κάνω εγώ διότι με τα καλλιτεχνικά δεν το έχω ...

**Comment by eirinichr** [comment]
Ρε παιδιά...!!! Κάποιοι δουλεύουμε τα Σάββατα και δεν προλάβαμε να τα διαβάσουμε όλα αυτά...!!! Εγώ θα το κάνω αυτό που είμαι καλή στα καλλιτεχνικά, αλλά δώσε μου λίγο χρόνο! Είναι η μόνη εργασία που έχουμε για μετά το πάσχα και πρέπει να τελειώσουμε άλλες πιο πριν. Θα το έχω όσο πιο σύντομα γίνεται. (Θα δω τι έχεις βάλει, θα αλλάξω λίγο την εργασία που έκανα στην html και θα το στείλω)

**Comment by anagno** [comment]
Όποιος ασχοληθεί με τα εμφανισιακά να με ρωτήσει... 
Όπως έχω φτιάξει τα αρχεία έχω προσπαθήσει να ξεχωρίσω την λογική από το εμφανισιακό κομμάτι. Το εμφανισιακό κομμάτι είναι στο common.inc.php στο οποίο προς το παρόν υπάρχουν οι συναρτήσεις του header και του footnote. Εκεί πρέπει να μπουν οι συναρτήσεις που θα καθορίζουν την εμφάνιση έτσι ώστε να ξεχωρίσει από το κομμάτι της λογικής που θα μπεί στα υπόλοιπα αρχεία...
Ξέρω δεν το περιγράφω ωραία γι` αυτό είπα όποιος ασχοληθεί να με ρωτήσει ... Αυτά ...
