### ISSUE TITLE
Στοιχεία για την βάση

### ISSUE THREAD

**Issue by anagno** [anagno/BookShop#4]
@GiannisVid Θα μας βρεις εσύ κανένα στοιχεία για την βάση ή πρέπει να ψάξουμε αλλού ;;;;

**Comment by GiannisVid** [comment]
Θα φέρω εγώ!

**Comment by anagno** [comment]
https://github.com/anagno/BookShop/commit/96d9f1243bb7a1e647a2e31cbaba0fc0b767cb61
https://github.com/anagno/BookShop/commit/5f640b51c82663f76853800fd32e44b0bd3de780

**Comment by anagno** [comment]
@GiannisVid  Είχες βάλει κανένα βιβλίο με 2 εκδόσεις ;;;


Σημείωση που δεν σε νοιάζει απλώς για να θυμάμαι : Κώδικας mysql για να εμφανίζει ποια βιβλία έχουν 2 εκδόσεις (select isbn, COUNT(book_id) as cnt from editions group by book_id having COUNT(book_id)>0; )

**Comment by GiannisVid** [comment]
Δεν έβαλα κανένα.

Στις 26 Φεβρουαρίου 2015 - 11:14 μ.μ., ο χρήστης Vasilis-Thanos
Anagnostopoulos <notifications@github.com> έγραψε:

**Comment by anagno** [comment]
Οκ ... Θα προσθέσω καμιά εικονική εγγραφή για να δοκιμάσουμε και αυτή την δυνατότητα ...

**Comment by anagno** [comment]
Να σε πω ... Στην βάση σας έχετε και καμιά εικόνα που μπορείς να εξάγεις αυτοματοποιημένα ;;; Ή μπα ;;;

**Comment by GiannisVid** [comment]
Billy sorry αλλά έλειπα από την παρασκευή για διακοπάρες και δεν είχα όρεξη να ασχοληθώ με τίποτα. Από αύριο θα ξεκινήσω να ασχολούμε με εργασίες. Σήμερα ξεκουράζομαι από το ταξίδι! Θα μιλήσουμε τηλεφωνικός αύριο να συνεννοηθούμε για όλα. Θα κανονίσουμε και να βρεθούμε, αλλά νομίζω καλύτερα μετά τα πληροφοριακά συστήματα για να είμαστε πιο άνετοι!

**Comment by anagno** [comment]
No problem ... Γι`  αυτό τα γράφω εδώ και όχι σε μαιλ. Ο καθένας όποτε έχει όρεξη ασχολείται ...
